<?php


/**
 * Implements hook_filter_info();
 */
function mcnasty_filter_info() {
  $filters = array();
  $filters['mcnasty'] = array(
    'title' => t('Filter out bad words'),
    'description' => t('Wash your keyboard out with soap'),
    'process callback' => 'mcnasty_filter_nasty_words',
  );

  return $filters;
}


function mcnasty_filter_nasty_words($text) {
  
  $filtered_text =  $text;
  $list_word = file_get_contents('badwords.txt', true);
  $expressions = '/\b('.$list_word.')\b/' ;
  $onlyconsonants = preg_replace($expressions, '[redacted]',  $filtered_text);
  return $onlyconsonants; 
}

/**
 * Validate the form and checks for badwords. Will phase through
 * but will send an error message. 
 */ 

function mcnasty_node_validate($node, $form, &$form_state) {

    $body_text = $form_state['values']['body'][LANGUAGE_NONE]['0']['value'];
    $filtered = mcnasty_filter_nasty_words($body_text);
    if ($body_text != $filtered) {
      drupal_set_message('WHOOPS! You used bad words. They will not show.. hahaha', $type = 'error', $repeat = FALSE);
    }

    
}